
package hawmetering;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HAWMeteringWebserviceService", targetNamespace = "http://hawmetering/", wsdlLocation = "http://localhost:9999/hawmetering/nw?wsdl")
public class HAWMeteringWebserviceService
    extends Service
{

    private final static URL HAWMETERINGWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException HAWMETERINGWEBSERVICESERVICE_EXCEPTION;
    private final static QName HAWMETERINGWEBSERVICESERVICE_QNAME = new QName("http://hawmetering/", "HAWMeteringWebserviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/hawmetering/nw?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HAWMETERINGWEBSERVICESERVICE_WSDL_LOCATION = url;
        HAWMETERINGWEBSERVICESERVICE_EXCEPTION = e;
    }

    public HAWMeteringWebserviceService() {
        super(__getWsdlLocation(), HAWMETERINGWEBSERVICESERVICE_QNAME);
    }

    public HAWMeteringWebserviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HAWMETERINGWEBSERVICESERVICE_QNAME, features);
    }

    public HAWMeteringWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, HAWMETERINGWEBSERVICESERVICE_QNAME);
    }

    public HAWMeteringWebserviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HAWMETERINGWEBSERVICESERVICE_QNAME, features);
    }

    public HAWMeteringWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HAWMeteringWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HAWMeteringWebservice
     */
    @WebEndpoint(name = "HAWMeteringWebservicePort")
    public HAWMeteringWebservice getHAWMeteringWebservicePort() {
        return super.getPort(new QName("http://hawmetering/", "HAWMeteringWebservicePort"), HAWMeteringWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HAWMeteringWebservice
     */
    @WebEndpoint(name = "HAWMeteringWebservicePort")
    public HAWMeteringWebservice getHAWMeteringWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hawmetering/", "HAWMeteringWebservicePort"), HAWMeteringWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HAWMETERINGWEBSERVICESERVICE_EXCEPTION!= null) {
            throw HAWMETERINGWEBSERVICESERVICE_EXCEPTION;
        }
        return HAWMETERINGWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
