
package hawmetering;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HAWMeteringWebservice", targetNamespace = "http://hawmetering/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HAWMeteringWebservice {


    /**
     * 
     * @param val
     */
    @WebMethod
    @Action(input = "http://hawmetering/HAWMeteringWebservice/setValueRequest", output = "http://hawmetering/HAWMeteringWebservice/setValueResponse")
    public void setValue(
        @WebParam(name = "val", partName = "val")
        double val);

    /**
     * 
     * @param title
     */
    @WebMethod
    @Action(input = "http://hawmetering/HAWMeteringWebservice/setTitleRequest", output = "http://hawmetering/HAWMeteringWebservice/setTitleResponse")
    public void setTitle(
        @WebParam(name = "title", partName = "title")
        String title);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://hawmetering/HAWMeteringWebservice/clearIntervalsRequest", output = "http://hawmetering/HAWMeteringWebservice/clearIntervalsResponse")
    public void clearIntervals();

    /**
     * 
     * @param min
     * @param color
     * @param max
     * @param label
     */
    @WebMethod
    @Action(input = "http://hawmetering/HAWMeteringWebservice/setIntervalsRequest", output = "http://hawmetering/HAWMeteringWebservice/setIntervalsResponse")
    public void setIntervals(
        @WebParam(name = "label", partName = "label")
        String label,
        @WebParam(name = "min", partName = "min")
        double min,
        @WebParam(name = "max", partName = "max")
        double max,
        @WebParam(name = "color", partName = "color")
        WebColor color);

    /**
     * 
     * @param min
     * @param max
     */
    @WebMethod
    @Action(input = "http://hawmetering/HAWMeteringWebservice/setRangeRequest", output = "http://hawmetering/HAWMeteringWebservice/setRangeResponse")
    public void setRange(
        @WebParam(name = "min", partName = "min")
        double min,
        @WebParam(name = "max", partName = "max")
        double max);

}
