
package hawsensor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SensorWebserviceService", targetNamespace = "http://wssensor/", wsdlLocation = "http://localhost:8888/hawsensor/?wsdl")
public class SensorWebserviceService
    extends Service
{

    private final static URL SENSORWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SENSORWEBSERVICESERVICE_EXCEPTION;
    private final static QName SENSORWEBSERVICESERVICE_QNAME = new QName("http://wssensor/", "SensorWebserviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/hawsensor/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENSORWEBSERVICESERVICE_WSDL_LOCATION = url;
        SENSORWEBSERVICESERVICE_EXCEPTION = e;
    }

    public SensorWebserviceService() {
        super(__getWsdlLocation(), SENSORWEBSERVICESERVICE_QNAME);
    }

    public SensorWebserviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENSORWEBSERVICESERVICE_QNAME, features);
    }

    public SensorWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, SENSORWEBSERVICESERVICE_QNAME);
    }

    public SensorWebserviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENSORWEBSERVICESERVICE_QNAME, features);
    }

    public SensorWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SensorWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SensorWebservice
     */
    @WebEndpoint(name = "SensorWebservicePort")
    public SensorWebservice getSensorWebservicePort() {
        return super.getPort(new QName("http://wssensor/", "SensorWebservicePort"), SensorWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SensorWebservice
     */
    @WebEndpoint(name = "SensorWebservicePort")
    public SensorWebservice getSensorWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wssensor/", "SensorWebservicePort"), SensorWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENSORWEBSERVICESERVICE_EXCEPTION!= null) {
            throw SENSORWEBSERVICESERVICE_EXCEPTION;
        }
        return SENSORWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
