
package hawsensor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import net.java.dev.jaxb.array.ObjectFactory;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SensorWebservice", targetNamespace = "http://wssensor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SensorWebservice {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wssensor/SensorWebservice/initializeMeterRequest", output = "http://wssensor/SensorWebservice/initializeMeterResponse")
    public boolean initializeMeter(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://wssensor/SensorWebservice/triggerSensorsRequest", output = "http://wssensor/SensorWebservice/triggerSensorsResponse")
    public void triggerSensors();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wssensor/SensorWebservice/getKoordinatorRequest", output = "http://wssensor/SensorWebservice/getKoordinatorResponse")
    public String getKoordinator();

    /**
     * 
     * @param meter
     * @param sensor
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wssensor/SensorWebservice/registerSensorRequest", output = "http://wssensor/SensorWebservice/registerSensorResponse")
    public boolean registerSensor(
        @WebParam(name = "meter", partName = "meter")
        String meter,
        @WebParam(name = "sensor", partName = "sensor")
        String sensor);

    /**
     * 
     * @param seqN
     */
    @WebMethod
    @Action(input = "http://wssensor/SensorWebservice/newTickRequest", output = "http://wssensor/SensorWebservice/newTickResponse")
    public void newTick(
        @WebParam(name = "seqN", partName = "seqN")
        int seqN);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://wssensor/SensorWebservice/uebertrageAktuellenStandRequest", output = "http://wssensor/SensorWebservice/uebertrageAktuellenStandResponse")
    public void uebertrageAktuellenStand();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wssensor/SensorWebservice/getMyUrlRequest", output = "http://wssensor/SensorWebservice/getMyUrlResponse")
    public String getMyUrl();

    /**
     * 
     * @param meter
     * @param sensor
     */
    @WebMethod
    @Action(input = "http://wssensor/SensorWebservice/setMeterAssignmentsRequest", output = "http://wssensor/SensorWebservice/setMeterAssignmentsResponse")
    public void setMeterAssignments(
        @WebParam(name = "sensor", partName = "sensor")
        StringArray sensor,
        @WebParam(name = "meter", partName = "meter")
        StringArray meter);

    /**
     * 
     * @param condition
     */
    @WebMethod
    @Action(input = "http://wssensor/SensorWebservice/setElectionPhaseRequest", output = "http://wssensor/SensorWebservice/setElectionPhaseResponse")
    public void setElectionPhase(
        @WebParam(name = "condition", partName = "condition")
        boolean condition);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://wssensor/SensorWebservice/electionAlgoRequest", output = "http://wssensor/SensorWebservice/electionAlgoResponse")
    public void electionAlgo();

    /**
     * 
     * @param newKoor
     */
    @WebMethod
    @Action(input = "http://wssensor/SensorWebservice/setKoordinatorRequest", output = "http://wssensor/SensorWebservice/setKoordinatorResponse")
    public void setKoordinator(
        @WebParam(name = "newKoor", partName = "newKoor")
        String newKoor);

}
